/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLoading: typeof import('./src/components/common/app-loading.vue')['default']
    BetterScroll: typeof import('./src/components/custom/better-scroll.vue')['default']
    DarkModeContainer: typeof import('./src/components/common/dark-mode-container.vue')['default']
    DarkModeSwitch: typeof import('./src/components/common/dark-mode-switch.vue')['default']
    EchartsAPI: typeof import('./src/components/Assembly/EchartsAPI.vue')['default']
    ExceptionBase: typeof import('./src/components/common/exception-base.vue')['default']
    HoverContainer: typeof import('./src/components/common/hover-container.vue')['default']
    LoadingEmptyWrapper: typeof import('./src/components/business/loading-empty-wrapper.vue')['default']
    LoginAgreement: typeof import('./src/components/business/login-agreement.vue')['default']
    NaiveProvider: typeof import('./src/components/common/naive-provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/custom/svg-icon.vue')['default']
    SystemLogo: typeof import('./src/components/common/system-logo.vue')['default']
  }
}
